version: "3.3"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_DATABASE: symfony-docker-test-admitad
      MYSQL_USER: root
      # MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  php-fpm:
    image: webdevops/php-dev:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql